# Generated by Django 3.2.6 on 2022-11-20 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Group A', max_length=55, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Uploads/Images/')),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_in_code', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_code_crash', models.CharField(blank=True, max_length=255, null=True)),
                ('exception', models.CharField(blank=True, max_length=255, null=True)),
                ('api', models.URLField(blank=True, max_length=255, null=True)),
                ('crated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_in_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
